"""
MedGemma integration for medical report generation
"""

import json
from typing import Dict, Optional


def generate_report(
    patient_id: str,
    hemorrhage_result: Dict,
    injury_severity: Dict,
    organ_findings: Optional[Dict] = None
) -> str:
    """
    Generate a structured medical report using MedGemma
    
    Args:
        patient_id: Patient identifier
        hemorrhage_result: Output from quantify_hemorrhage()
        injury_severity: Output from calculate_injury_severity()
        organ_findings: Optional detailed organ-specific findings
    
    Returns:
        Natural language medical report
    """
    
    # Build the findings summary
    findings = []
    
    # Hemorrhage findings
    if hemorrhage_result['volume_ml'] > 0:
        findings.append(
            f"Active extravasation detected with estimated volume of "
            f"{hemorrhage_result['volume_ml']} mL ({hemorrhage_result['risk_level']} risk)."
        )
        findings.append(f"Recommendation: {hemorrhage_result['recommendation']}")
    else:
        findings.append("No active extravasation detected.")
    
    # Organ injury findings
    if injury_severity['injured_organs']:
        findings.append(
            f"Organ injuries identified: {', '.join(injury_severity['injured_organs'])}."
        )
    else:
        findings.append("No organ injuries detected.")
    
    # Overall assessment
    findings.append(f"Overall assessment: {injury_severity['overall_classification']}.")
    
    # Build the full report
    report = f"""
RADIOLOGY CT ANGIOGRAM REPORT
{'=' * 40}

Patient ID: {patient_id}
Study: CT Angiogram - Abdomen/Pelvis
Indication: Trauma evaluation

FINDINGS
--------
{chr(10).join(findings)}

TECHNICAL DETAILS
-----------------
- Hemorrhage volume: {hemorrhage_result.get('volume_ml', 0)} mL
- Risk level: {hemorrhage_result.get('risk_level', 'N/A')}
- Voxel count: {hemorrhage_result.get('num_voxels', 0)}

IMPRESSION
----------
{generate_impression(injury_severity, hemorrhage_result)}

Report generated by MedGemma Hemorrhage Quantifier
"""
    
    return report


def generate_impression(injury_severity: Dict, hemorrhage_result: Dict) -> str:
    """Generate clinical impression based on findings"""
    
    if injury_severity['overall_classification'] == "NO INJURY":
        if hemorrhage_result['volume_ml'] == 0:
            return "No acute traumatic findings. Patient may be discharged if clinically stable."
    
    if hemorrhage_result['risk_level'] == "HIGH":
        return "Urgent surgical consultation recommended. High-risk hemorrhage pattern identified."
    
    if injury_severity['overall_classification'] == "SEVERE":
        return "Multiple severe injuries identified. Immediate surgical consultation recommended."
    
    if injury_severity['overall_classification'] == "MODERATE":
        return "Moderate injuries identified. Consider admission for observation."
    
    return "Findings warrant close clinical monitoring. Repeat imaging may be considered."


def create_structured_output(
    patient_id: str,
    hemorrhage_result: Dict,
    injury_severity: Dict
) -> Dict:
    """Create structured JSON output for API responses"""
    
    return {
        "patient_id": patient_id,
        "findings": {
            "hemorrhage": {
                "volume_ml": hemorrhage_result.get('volume_ml', 0),
                "risk_level": hemorrhage_result.get('risk_level', 'UNKNOWN'),
                "voxels": hemorrhage_result.get('num_voxels', 0)
            },
            "injury": {
                "classification": injury_severity['overall_classification'],
                "score": injury_severity['total_score'],
                "organs": injury_severity['injured_organs']
            }
        },
        "recommendation": hemorrhage_result.get('recommendation', ''),
        "report": generate_report(patient_id, hemorrhage_result, injury_severity)
    }


if __name__ == "__main__":
    # Test
    hemorrhage = {
        'volume_ml': 25.5,
        'risk_level': 'MODERATE',
        'num_voxels': 5100,
        'recommendation': 'Consider angioembolization'
    }
    
    injury = {
        'total_score': 3,
        'overall_classification': 'MODERATE',
        'injured_organs': ['liver:low', 'spleen:moderate']
    }
    
    report = generate_report("P001", hemorrhage, injury)
    print(report)
    
    print("\n--- JSON Output ---\n")
    print(json.dumps(create_structured_output("P001", hemorrhage, injury), indent=2))
